dataset_config = "./dataset/dataset_img.toml"
discrete_flow_shift = 7
#dit = "/media/philipp-haderer/data/stable_diffusion/models/diffusion_models/HunyuanVideo_comfy/FramePackI2V_HY_bf16.safetensors"
dit = "/home/philipp-haderer/Dokumente/FramePack-Studio/hf_download/hub/models--lllyasviel--FramePack_F1_I2V_HY_20250503/snapshots/ab239828e0b384fed75580f186f078717d4020f7"
dit_dtype = "bfloat16"
gradient_accumulation_steps = 1
gradient_checkpointing = true
guidance_scale = 1
huggingface_token = ""
max_train_epochs = 5
max_train_steps = 5000
learning_rate = 2e-4
log_with = "tensorboard" # values: tensorboard,wandb,all
logging_dir = "./dataset/data/output/framepack/julia_forstner"
logit_std = 1
lr_scheduler = "constant"
lr_scheduler_num_cycles = 1
lr_scheduler_power = 1
lr_warmup_steps = 0
max_data_loader_n_workers = 3
max_grad_norm = 1
max_timestep = 1000
mixed_precision = "bf16"
mode_scale = 1.29
network_alpha = 1
network_dim = 32
network_module = "networks.lora_framepack"
optimizer_type = "adamw8bit"
output_dir = "./dataset/data/output/framepack/julia_forstner"
output_name = "julia_forstner"
persistent_data_loader_workers = true
save_every_n_epochs = 5
save_last_n_epochs_state = 1
save_state_on_train_end = true
sdpa = true
seed = 42
sigmoid_scale = 1
split_attn = true
text_encoder1 = "/home/philipp-haderer/Dokumente/FramePack/hf_download/hub/models--hunyuanvideo-community--HunyuanVideo/snapshots/e8c2aaa66fe3742a32c11a6766aecbf07c56e773"
text_encoder2 = "/home/philipp-haderer/Dokumente/FramePack/hf_download/hub/models--hunyuanvideo-community--HunyuanVideo/snapshots/e8c2aaa66fe3742a32c11a6766aecbf07c56e773"
image_encoder = "/home/philipp-haderer/Dokumente/FramePack-Studio/hf_download/hub/models--lllyasviel--flux_redux_bfl/snapshots/45b801affc54ff2af4e5daf1b282e0921901db87"
timestep_sampling = "shift"
vae = "/home/philipp-haderer/Dokumente/FramePack-Studio/hf_download/hub/models--hunyuanvideo-community--HunyuanVideo/snapshots/e8c2aaa66fe3742a32c11a6766aecbf07c56e773"
vae_chunk_size = 32
vae_dtype = "float16"
vae_spatial_tile_sample_min_size = 256
vae_tiling = true
weighting_scheme = "none"
