# resolution, caption_extension, batch_size, num_repeats, enable_bucket, bucket_no_upscale should be set in either general or datasets
# otherwise, the default values will be used for each item

# general configurations
[general]
resolution = [960, 544, 640]
caption_extension = ".txt"
batch_size = 1
enable_bucket = true
bucket_no_upscale = false

[[datasets]]
fp_latent_window_size = 9
image_directory = "/home/philipp-haderer/Dokumente/musubi-tuner/dataset/input"
cache_directory = "/home/philipp-haderer/Dokumente/musubi-tuner/dataset/input/cache"
num_repeats = 1 # optional, default is 1. Number of times to repeat the dataset. Useful to balance the multiple datasets with different sizes.

[[datasets]]
video_directory = "/home/philipp-haderer/Dokumente/musubi-tuner/dataset/input"
control_directory = "/home/philipp-haderer/Dokumente/musubi-tuner/dataset/input" # required for dataset with control videos
cache_directory = "/home/philipp-haderer/Dokumente/musubi-tuner/dataset/input/cache"
target_frames = [1, 25, 45]
frame_extraction = "head"
